plugins {
    id 'com.android.application'
}

android {
    compileSdk 23
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "com.filmstreamer"
        minSdk 21
        targetSdk 23
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
}
